apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-app-dev
spec:
  replicas: {{ .Values.rep_set.details_app }}
  selector:
    matchLabels:
      app: details-app-dev
      version: latest
  template:
    metadata:
      labels:
        app: details-app-dev
        version: latest
    spec:
      containers:
        - name: details-app-dev
          env:          
            - name: POSTGRES_USER
              value: {{ .Values.db_pg.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.secrets.POSTGRES_PASSWORD }}  # Use decrypted secret
            - name: SECRET_KEY
              value: {{ .Values.secrets.SECRET_KEY }}  # Use decrypted secret
            - name: DBHOST
              value: {{ .Values.db_pg.DBHOST }}
            - name: DBNAME
              value: {{ .Values.db_pg.DBNAME }}
          image: {{ .Values.images.details_app }}
          ports:
            - containerPort: 8000 # This is the internal container port
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
spec:
  replicas: {{ .Values.rep_set.postgres }}
  selector:
    matchLabels:
      app: postgres-dev
      version: latest
  template:
    metadata:
      labels:
        app: postgres-dev
        version: latest
    spec:
      hostname: postgres-dev-container
      volumes:
      - name: postgres-dev-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
        - name: postgres-dev
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db_pg.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: {{ .Values.db_pg.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.secrets.POSTGRES_PASSWORD }}  # Use decrypted secret
          image: {{ .Values.images.postgres }}

          ports:
            - containerPort: 5432 # This is the internal container port
          volumeMounts:
            - name: postgres-dev-storage
              mountPath: /var/lib/dev_postgresql/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        