apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: details-app-dev-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"spec:
spec:
  rules:
  - host: dev.10.0.0.1
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: details-app-dev-service
            port:
              number: 8000
  tls:
  - hosts:
    - dev.10.0.0.1
    secretName: prod-tls