apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: details-app-dev-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - dev-cloudforge.duckdns.org
      secretName: details-app-tls
  rules:
  - host: dev-cloudforge.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: details-app-dev-service
            port:
              number: 8000