apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-dev-pv
  labels: 
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/dev_postgres # This is the path on the host where the data will be stored
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "postgres-dev"

  nodeAffinity: # Bind PV to a specific node using its hostname
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-master