apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev-pvc
spec:
  storageClassName: "postgres-dev"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local