apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudforge-prod
  namespace: cert-manager
spec:
  acme:
    email: admin@cloudforge.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudforge-prod
    solvers:
      - http01:
          ingress:
            class: nginx