apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: details-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  # tls:
  #   - hosts:
  #     - details-app-prod.local
  #     secretName: details-app-tls
  rules:
  - host: details-app-prod.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: details-app-service
            port:
              number: 8000