apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: details-app-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: traefik
  labels:
    app: nginx
spec:
  rules:
  - host: details-app-prod.local
    http:
      paths:
      - backend:
          service:
            name: details-app-service
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
    - hosts:
      - details-app-prod.local
      secretName: details-app-tls
