version: "2"
services:
    main-task:
        hostname: jenkins-main-task
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "800:800"
        networks:
            - jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock    
            - ./conf_files:/var/jenkins_home/

    
    worker1-task:
        hostname: jenkins-worker1-task
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - jenkins
        environment:
            SSH_USERNAME: jenkins
            SSH_USERPASS: jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock    
            - ../reports:/home/jenkins/reports/
networks: 
  jenkins:
    driver: bridge