name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      docker_username:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      docker_password:
        required: true


jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ inputs.DOCKER_USERNAME }}/${{ inputs.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ inputs.DOCKER_USERNAME }}/${{ inputs.IMAGE_NAME }}:2.1.${{ github.run_number }}, ${{ inputs.DOCKER_USERNAME }}/${{ inputs.IMAGE_NAME }}:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ inputs.DOCKER_USERNAME }}/${{ inputs.IMAGE_NAME }}:2.1.${{ github.run_number }}
          subject-digest: ${{ steps.push.outputs.digest }}