name: deploy application

on: 
  push:
    branches:
      - details_app_dev
jobs:
  deploy:
    runs-on: ubuntu-latest

    env: # Define environment variables
      DOCKER_USERNAME: your-username-variable-here

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin