name: deploy application

on: 
  push:
    branches:
      - details_app_dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: details_app_dev


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin && ls -la