name: deploy application

on: 
  push:
    branches:
      - details_app_dev
jobs:
  docker-build:
    name: Build&Push development image
    runs-on: ubuntu-latest
    
    steps:
      - name: Testing
        run: |
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_REPOSITORY_OWNER"
          echo "$DOCKER_USERNAME"
 
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: "$DOCKER_USERNAME"
          password: "$DOCKER_PASSWORD"
      
      # - name: Building the image
      #   run: docker build -t "details_app:test" .
      
      # - name: Tagging the image
      #   run: docker tag details_app:test ${{ vars.DOCKER_USERNAME }} /details_app:test

      # - name: Pushing the image
      #   run: docker push alayani/details_app:test    