name: Main Workflow

on:
  push:
    branches:
      - details_app_dev

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
    
        steps:
            uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
            # env:
            #     DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
            #     DOCKER_PASSWORD: ${{ vars.DOCKER_PASSWORD }}
            with:
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ env.DOCKER_PASSWORD }}
              
    call_reusable_workflow:
        name: Call Reusable Workflow
        uses: ./.github/workflows/build_push.yml
        with:
            environment: details_app_dev
        #     docker_username: ${{ vars.DOCKER_USERNAME }}
        #     image_name: ${{ vars.IMAGE_NAME }}
        # secrets:
        #     docker_password: ${{ secrets.DOCKER_PASSWORD }}