name: Main Workflow

on:
  push:
    branches:
      - details_app_dev

jobs:
  call_reusable_workflow:
    name: Call Reusable Workflow
    uses: ./.github/workflows/build_push.yml
    with:
      environment: details_app_dev
      docker_username: ${{ vars.DOCKER_USERNAME }}
      image_name: ${{ vars.IMAGE_NAME }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}